### ISSUE TITLE
Item Filter

### ISSUE THREAD

**Issue by RuizuKun-Dev** [MrKinau/FishingBot#98] opened 2020-11-19 20:06 UTC
We use the AFk fishing bot for different reasons, some of us want Fish, some of us want Enchanted Books, some of us want other kinds of loot.

It would be nice to have an item Filter feature, so the bot automatically throws away items that are blacklisted or keeps items that are whitelisted.

**Comment by Summerfeeling** [comment] 2020-11-19 20:08
Thanks for your suggestion! This is a duplicate of #28. We are aware of this idea but do not have a good solution yet. But we will implement this as soon as possible! :)

**Closed by Summerfeeling** 2020-11-19 20:08 UTC
