### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by Septan** [MrKinau/FishingBot#137] opened 2021-07-06 05:45 UTC
```
[2021-07-03 23:28:42] [INFO   ] Configuration was loaded: E:\Downloads\New folder\config.json 
[2021-07-03 23:28:42] [INFO   ] Trying to authenticate with ************@gmail.com:************ (MICROSOFT)... 
[2021-07-03 23:28:45] [INFO   ] Authentication successful! 
[2021-07-03 23:28:45] [INFO   ] java.lang.NullPointerException: Cannot invoke "com.github.steveice10.mc.auth.data.GameProfile.getIdAsString()" because the return value of "com.github.steveice10.mc.auth.service.MsaAuthenticationService.getSelectedProfile()" is null 
[2021-07-03 23:28:45] [INFO   ]     at systems.kinau.fishingbot.auth.MicrosoftAuthenticator.authenticate(MicrosoftAuthenticator.java:22) 
[2021-07-03 23:28:45] [INFO   ]     at systems.kinau.fishingbot.auth.Authenticator.authenticate(Authenticator.java:50) 
[2021-07-03 23:28:45] [INFO   ]     at systems.kinau.fishingbot.Bot.authenticate(Bot.java:275) 
[2021-07-03 23:28:45] [INFO   ]     at systems.kinau.fishingbot.Bot.<init>(Bot.java:136) 
[2021-07-03 23:28:45] [INFO   ]     at systems.kinau.fishingbot.FishingBot.startBot(FishingBot.java:80) 
[2021-07-03 23:28:45] [INFO   ]     at systems.kinau.fishingbot.gui.GUIController.lambda$startStop$1(GUIController.java:214) 
[2021-07-03 23:28:45] [INFO   ]     at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by MrKinau** [comment] 2021-07-22 01:56
Should be fixed. As I could not reproduce this, try the [latest release](https://github.com/MrKinau/FishingBot/releases/tag/2.7.17). It might not work for realms.

If you have any issues create a new issue.

**Closed by MrKinau** 2021-07-22 01:56 UTC
