### ISSUE TITLE
Unable To Ping

### ISSUE THREAD

**Issue by Bogashi** [MrKinau/FishingBot#78] opened 2020-10-08 02:30 UTC
When I start the script it says pinging xxx, the it says unable to ping xxx.

It says my ip not the xxx just don’t want to share it.

Also, would this work if I use optifine?

**Comment by MrKinau** [comment] 2020-10-08 07:12
Have you edited the config.json? (see [here](https://github.com/MrKinau/FishingBot/wiki#how-do-i-use-the-bot))
At least you have to set your credentials in account and your server connection in server.

The bot does not require any Minecraft instance and is completely independent from your currently running minecraft instance.

**Comment by MrKinau** [comment] 2020-10-09 20:15
As you have not answered I assume the issue is fixed and I'll close it. If your issue is not fixed yet, please open another issue

**Closed by MrKinau** 2020-10-09 20:15 UTC
