### ISSUE TITLE
Wrong login failure output

### ISSUE THREAD

**Issue by SAFEluren** [MrKinau/FishingBot#163] opened 2022-04-08 00:18 UTC
I have been unable to log in to this program with my Microsoft account.After I checked Summerfeeling's reply to #158,I closed 2fa and successfully logged in. However, the error of unable to log in caused by 2FA is: "Invalid username and/or password",And my Microsoft authenticator has received a login request.(https://pastebin.ubuntu.com/p/C2P2GnMJzj/)

**Comment by MrKinau** [comment] 2022-04-08 23:49
Sorry for that, but the authentication seems to not work for any microsoft account, however the auth library does not provide other ifromation than "Invalid username and/or password". There were plans on implementing an alternative authentication method (using a browser), but I cant say if and when it gets implemented. So far if you cant find another solution to fix this problem (e.g. other account) you're stuck. I'll close this issue, because it's a duplicate of #158

**Closed by MrKinau** 2022-04-08 23:49 UTC
