### ISSUE TITLE
Bot doesn't start fishing when internet connection is bad

### ISSUE THREAD

**Issue by RootRobo** [MrKinau/FishingBot#32] opened 2020-03-18 17:15 UTC
If the bot has a bad internet connection and the option stucking-fix-enabled is set to false, the bot doesn't even try to start fishing.

**Comment by RootRobo** [comment] 2020-03-18 17:17
Oh, and I have issues to import the project into my IDE (IntelliJ)
Importing works, but the dependencys wont install (maybe Im just dumb, but I never used Maven before)

**Comment by MrKinau** [comment] 2020-04-03 15:23
Well, I will try to reproduce it andy maybe start the bot later after the complete login process is done

**Comment by MrKinau** [comment] 2020-06-07 12:39
Sorry, I could not reproduce this.
tested it with limited bandwith to 512kbit/s which was the lowest my switch could arrange. Can you apply instructions on how to reproduce this?

**Comment by MrKinau** [comment] 2020-07-05 21:58
As there are no further hints, I'll close this issue. Just re-create it if anyone can find a way to reproduce this

**Closed by MrKinau** 2020-07-05 21:58 UTC
Labels: bug, help wanted
