### ISSUE TITLE
cant connect to 1.19.2 server

### ISSUE THREAD

**Issue by ENTNEAZ** [MrKinau/FishingBot#174] opened 2022-08-31 03:32 UTC
I'm trying to connect a 1.19.2 server
and the bot goes online and immediately goes offline

and the console appear this

```
Exception in thread "Thread-10" [2022-08-31 11:07:51] [INFO] java.lang.NullPointerException: Cannot invoke "systems.kinau.fishingbot.bot.Player.getHeldItem()" because the return value of "systems.kinau.fishingbot.Bot.getPlayer()" is null
[2022-08-31 11:07:51] [INFO]       at systems.kinau.fishingbot.modules.fishing.FishingModule.lambda$onSetDifficulty$7(FishingModule.java:293)
[2022-08-31 11:07:51] [INFO]       at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Thread-9" [2022-08-31 11:07:51] [INFO] java.util.concurrent.RejectedExecutionException: Task systems.kinau.fishingbot.Bot$$Lambda$1171/0x000000080110eeb0@254d5d8 rejected from java.util.concurrent.ThreadPoolExecutor@3e8732ac[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
[2022-08-31 11:07:51] [INFO]       at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
[2022-08-31 11:07:51] [INFO]       at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
[2022-08-31 11:07:51] [INFO]       at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
[2022-08-31 11:07:51] [INFO]       at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:721)
[2022-08-31 11:07:51] [INFO]       at systems.kinau.fishingbot.Bot.runCommand(Bot.java:290)
[2022-08-31 11:07:51] [INFO]       at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$null$0(ClientDefaultsModule.java:50)
[2022-08-31 11:07:51] [INFO]       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-08-31 11:07:51] [INFO]       at systems.kinau.fishingbot.modules.ClientDefaultsModule.lambda$onSetDifficulty$1(ClientDefaultsModule.java:49)

```
(server version: paper 1.19.2 #135)
(and I also tried to connect to a 1.19.2 vanilla server, but the result is same)

this is the server log:
```
[11:24:04] [Server thread/INFO]: MyName[/127.0.0.1:63291] logged in with entity id 1253 at (-189.31878935693035, 63.0, -35.95213729251354)
[11:24:04] [Server thread/INFO]: MyName joined the game
[11:24:04] [Server thread/INFO]: MyName lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 1253 out of bounds for length 7
[11:24:04] [Server thread/INFO]: MyName left the game
```

**Comment by ENTNEAZ** [comment] 2022-08-31 03:34
bot version is 2.9.2

**Comment by MrKinau** [comment] 2022-08-31 13:10
Can you send the full log (maybe activate "log packets (debug only)" as well), the exception you've sent is not the root cause of this issue. Is there any special setting related to your Microsoft account? Set age below Minecraft age restriction or Minecraft purchased through XBox Game Pass or sth. like this?

**Comment by MrKinau** [comment] 2022-08-31 14:40
I've published a new release with a bugfix, the packet that handles the auto sneak had the wrong packet id and that's why the server kicked the bot. It whould work now, if you experience any further issue feel free to create a new issue :)

Fixed in: https://github.com/MrKinau/FishingBot/releases/tag/2.9.3

**Closed by MrKinau** 2022-08-31 14:40 UTC

**Comment by ENTNEAZ** [comment] 2022-08-31 14:47
ok thank you
